package my.group.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CalculatorWs", targetNamespace = "http://superbiz.org/wsdl")
public interface CalculatorWs {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "multiply", targetNamespace = "http://superbiz.org/wsdl", className = "my.group.ws.Multiply")
	@ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://superbiz.org/wsdl", className = "my.group.ws.MultiplyResponse")
	public int multiply(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sum", targetNamespace = "http://superbiz.org/wsdl", className = "my.group.ws.Sum")
	@ResponseWrapper(localName = "sumResponse", targetNamespace = "http://superbiz.org/wsdl", className = "my.group.ws.SumResponse")
	public int sum(@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

}
