package my.group.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CalculatorService service = new CalculatorService();
 * CalculatorWs portType = service.getCalculatorPort();
 * portType.multiply(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CalculatorService", targetNamespace = "http://superbiz.org/wsdl", wsdlLocation = "file:/K:/git/ejb-test/helloWorld-ws/src/main/resources/calculator.wsdl")
public class CalculatorService extends Service {

	private final static URL CALCULATORSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(my.group.ws.CalculatorService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = my.group.ws.CalculatorService.class.getResource(".");
			url = new URL(baseUrl,
					"file:/K:/git/ejb-test/helloWorld-ws/src/main/resources/calculator.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/K:/git/ejb-test/helloWorld-ws/src/main/resources/calculator.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CALCULATORSERVICE_WSDL_LOCATION = url;
	}

	public CalculatorService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CalculatorService() {
		super(CALCULATORSERVICE_WSDL_LOCATION, new QName(
				"http://superbiz.org/wsdl", "CalculatorService"));
	}

	/**
	 * 
	 * @return returns CalculatorWs
	 */
	@WebEndpoint(name = "CalculatorPort")
	public CalculatorWs getCalculatorPort() {
		return super.getPort(new QName("http://superbiz.org/wsdl",
				"CalculatorPort"), CalculatorWs.class);
	}

}
